# Configuration.

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - '**/Guardfile'
    - 'bin/bundle'
    - 'db/**/*'

Style/For:
  Exclude:

Style/FrozenStringLiteralComment:
  Description: >-
                 Add the frozen_string_literal comment to the top of files
                 to help transition to frozen string literals by default.
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: true
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods:
    # By default, exclude the `#refine` method, as it tends to have larger
    # associated blocks.
    - refine
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'
